### ISSUE TITLE
What's the point of open-sourcing the weights without inference code ?

### ISSUE THREAD

**Issue by lilong-wen** [CVI-SZU/STKM#8]
I came across this paper by accident and found a GitHub link at the end of abstraction. And I thought, "cool, this paper really did something". But after I clicked it and found two links to the pre-trained weights of ResNet50 and even a License file but without any codes. It's just hilarious, bro. What's the point of open-source a weight file without inference code ? shame on you, CVI-SZU ! It's immoral to claim open-source in the paper just to trick the reviewers.

**Comment by WQ1436317135** [comment]
The code and checkpoints are available now.
